spin_manifest_version = 2

[application]
name = "wasip2-golang"
version = "0.2.0"
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = ""

[variables]
secret = { required = true }

[[trigger.http]]
route = "/..."
component = "wasip2-golang"

[component.wasip2-golang]
source = "main.wasm"
allowed_outbound_hosts = ["https://google.com"]
ai_models = ["llama2-chat"]
key_value_stores = ["default"]
[component.wasip2-golang.variables]
password = "{{ secret }}"
[component.wasip2-golang.build]
command = "tinygo build -x -target=wasip2 --wit-package ./wit --wit-world http-trigger -o main.wasm -x -work main.go"
watch = ["**/*.go", "go.mod"]
